name: Manual Approval Workflow

on:
  push:
  issue_comment:
    types:
      - created

jobs:
  manual_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Manual Approval
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const approvers = ['user1', 'user2', 'org/team1'];

            if (approvers.includes(context.payload.comment.user.login) && comment.toLowerCase().includes('approve')) {
              // The comment is an approval from an allowed user
              core.setOutput('approval', 'true');
            }
        id: approval

      - name: Deploy if Approved
        if: steps.manual_approval.outputs.approval == 'true'
        run: |
          echo "testing"

